[package]
name = "wallet_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btc_only_wallet_rust_c = {path = "src/btc_only_wallet", default-features = false, optional = true}
multi_coins_wallet_rust_c = {path = "./src/multi_coins_wallet",  optional = true}

[features]
default = ["multi-coins"]
multi-coins = ["btc_only_wallet_rust_c/multi-coins","multi_coins_wallet_rust_c"]
btc-only = ["btc_only_wallet_rust_c/btc-only"]