[package]
name = "general_test_cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { workspace = true }
app_utils = { workspace = true }
rust_tools = { workspace = true }
cty = { workspace = true }
cstr_core = { workspace = true }
hex = { workspace = true }
ur-registry = { workspace = true }
common_rust_c = { workspace = true }
wallet_rust_c = { workspace = true }

[features]
default = ["multi-coins"]
multi-coins = [
    "common_rust_c/multi-coins",
    "wallet_rust_c/multi-coins"
]
btc-only = [
    "common_rust_c/btc-only",
    "wallet_rust_c/btc-only"
]