[package]
name = "cosmos_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { workspace = true }
app_cosmos = { workspace = true, default-features = false }
app_utils = { workspace = true }
rust_tools = { workspace = true }
cty = { workspace = true }
cstr_core = { workspace = true }
either = { workspace = true }
serde_json = { workspace = true }
ur-registry = { workspace = true }

common_rust_c = { workspace = true }

[features]
debug-memory = []
