[package]
name = "common_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { workspace = true }
cty = { workspace = true }
cstr_core = { workspace = true }
app_utils = { workspace = true }
rust_tools = { workspace = true }
base64 = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
ur-registry = { workspace = true }
serde_json = { workspace = true }   
bitcoin = { workspace = true }
bitcoin_hashes = { workspace = true }
rsa = { workspace = true }
cryptoxide = { workspace = true }
ur-parse-lib = { workspace = true }
sha1 = { workspace = true }

app_bitcoin = { workspace = true }
app_wallets = { workspace = true }

app_ethereum = { path = "../../../apps/ethereum", optional = true }
app_cardano = {path = "../../../apps/cardano", optional = true}
app_tron = { path = "../../../apps/tron", optional = true }
app_solana = { path = "../../../apps/solana", optional = true }
app_near = { path = "../../../apps/near", optional = true }
app_xrp = {path = "../../../apps/xrp", optional = true }
app_cosmos = {path = "../../../apps/cosmos", default-features = false, optional = true}
app_aptos = {path = "../../../apps/aptos", default-features = false, optional = true}
app_sui = {path = "../../../apps/sui", optional = true}
app_arweave = {path = "../../../apps/arweave", optional = true}
app_stellar = {path = "../../../apps/stellar", optional = true}
app_ton = {path = "../../../apps/ton", optional = true}
app_monero = {path = "../../../apps/monero", optional = true}

[features]
debug-memory = ["default"]
default = ["multi-coins"]
multi-coins = ["app_ethereum", "app_cardano", "app_tron", "app_solana", "app_near", "app_xrp", "app_cosmos", "app_aptos", "app_sui", "app_arweave", "app_ton", "app_stellar", "app_monero"]
#
btc-only = []