[package]
name = "rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common_rust_c = { workspace = true, default-features = false, optional = true }
bitcoin_rust_c = { workspace = true, default-features = false, optional = true }
wallet_rust_c = { workspace = true, default-features = false, optional = true }
test_cmd = { path = "./src/test_cmd", default-features = false, optional = true }

ethereum_rust_c = { workspace = true, optional = true }
solana_rust_c = { workspace = true, optional = true }
aptos_rust_c = { workspace = true, optional = true }
near_rust_c = { workspace = true, optional = true }
cosmos_rust_c = { workspace = true, optional = true }
cardano_rust_c = { workspace = true, optional = true }
sui_rust_c = { workspace = true, optional = true }
tron_rust_c = { workspace = true, optional = true }
xrp_rust_c = { workspace = true, optional = true }
arweave_rust_c = { workspace = true, optional = true }
stellar_rust_c = { workspace = true, optional = true }
ton_rust_c = { workspace = true, optional = true }
simulator_rust_c = { workspace = true, optional = true, default-features = false }

cty = { workspace = true }
cstr_core = { workspace = true }

[lib]
crate-type = ["staticlib"]

[features]
use-allocator = []
firmware = ["use-allocator", "multi-coins"]
firmware-btc-only = ["use-allocator", "btc-only"]
simulator = ["multi-coins", "sui_rust_c/simulator", "simulator_rust_c/multi-coins"]
simulator_btc_only = ["btc-only", "simulator_rust_c/btc-only"]
default = ["simulator"]

debug-memory = [
    "multi-coins",
    "common_rust_c/debug-memory",
    "ethereum_rust_c/debug-memory",
    "bitcoin_rust_c/debug-memory",
    "wallet_rust_c/debug-memory",
    "test_cmd/debug-memory",
    "solana_rust_c/debug-memory",
    "aptos_rust_c/debug-memory",
    "near_rust_c/debug-memory",
    "cosmos_rust_c/debug-memory",
    "cardano_rust_c/debug-memory",
    "sui_rust_c/debug-memory",
    "tron_rust_c/debug-memory",
    "xrp_rust_c/debug-memory",
    "ton_rust_c/debug-memory",
]

multi-coins = [
    "common_rust_c/multi-coins",
    "bitcoin_rust_c/multi-coins",
    "wallet_rust_c/multi-coins",
    "test_cmd/multi-coins",
    "ethereum_rust_c",
    "solana_rust_c",
    "aptos_rust_c",
    "near_rust_c",
    "cosmos_rust_c",
    "cardano_rust_c",
    "sui_rust_c",
    "tron_rust_c",
    "xrp_rust_c",
    "arweave_rust_c",
    "stellar_rust_c",
    "ton_rust_c",
]
btc-only = [
    "common_rust_c/btc-only",
    "bitcoin_rust_c/btc-only",
    "wallet_rust_c/btc-only",
    "test_cmd/btc-only",
]
test_feature = []
[dev-dependencies]
keystore = { path = "../keystore" }

[patch.crates-io.bitcoin]
git = "https://github.com/KeystoneHQ/rust-bitcoin.git"
tag = "v0.31.2"
default-features = false
features = ["no-std", "secp-recovery"]
