include_guard = "_LIBRUST_C_H"

after_includes = "#define BUILD_MULTI_COINS\n#define SIMPLERESPONSE_C_CHAR_MAX_LEN 2048\n#define ADDRESS_MAX_LEN 256\n#define PATH_ITEM_MAX_LEN 32"

language = "C"

[defines]
"feature = multi-coins" = "BUILD_MULTI_COINS"

[parse]
extra_bindings = ["rust_c"]

[parse.expand]
crates = ["rust_c"]
default_features = false