[package]
name = "arweave_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { workspace = true }
app_utils = { workspace = true }
app_arweave = { workspace = true }
rust_tools = { workspace = true }
common_rust_c = { path = "../common" }
cty = { workspace = true }
cstr_core = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
bitcoin = { workspace = true }
ur-registry = { workspace = true }
cryptoxide = { workspace = true }
