[package]
name = "ethereum_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { workspace = true, default-features = false }
app_ethereum = { workspace = true }
app_utils = { workspace = true }
rust_tools = { workspace = true }
cty = { workspace = true }
cstr_core = { workspace = true }
itertools = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
ur-registry = { workspace = true }
core2 = { workspace = true }
cryptoxide = { workspace = true }
bitcoin = { workspace = true }
common_rust_c = { workspace = true }

[features]
debug-memory = []
