[package]
name = "solana_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { workspace = true, default-features = false }
app_solana = { workspace = true }
rust_tools = { workspace = true }
cty = { workspace = true }
cstr_core = { workspace = true }
itertools = { workspace = true }
common_rust_c = { path = "../common" }
ur-registry = { workspace = true }
app_utils = { workspace = true }

[features]
debug-memory = []
