[package]
name = "keystore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "0.2.2"
cstr_core = "0.2.6"
third_party = { path = "../third_party" }
rust_tools = { path = "../tools" }
rand_chacha = { version="0.3.1", default-features=false }
arrayref = "0.3.6"
sha2 = { version = "0.10.6", default-features = false, features = ["oid"] }
num-bigint-dig = { version = "0.8.2", default-features=false }

[features]
default = ["std"]
std = []
rsa = []