[package]
name = "stellar_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { workspace = true }
app_utils = { workspace = true }
app_stellar = { workspace = true }
common_rust_c = { workspace = true }
cty = "0.2.2"
cstr_core = "0.2.6"
hex = { workspace = true }
ur-registry = { workspace = true }