on:
  push:
    tags:
      - '2.88.0'

name: On Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: release/v${{ github.ref_name }}
          title: "Release v${{ github.ref_name }}"
          body: |
            ## Release ${{ github.ref_name }}
            
            This is an automated pull request created for release ${{ github.ref_name }}.
            
            ### Changes
            - Release version: ${{ github.ref_name }}
            - Created from tag: ${{ github.ref }}
            
            Please review and merge this pull request to update the master branch with the release changes.
          commit-message: "Release ${{ github.ref_name }}"
          delete-branch: true