on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

name: On Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Merge Branch
        run: |
          git fetch origin release/v${{ github.ref_name }}
          git checkout origin/release/v${{ github.ref_name }}
          git checkout -b merge/v${{ github.ref_name }}
          git push origin merge/v${{ github.ref_name }}

      - name: Create Pull Request
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/keystonehq/keystone3-firmware/pulls \
          -d '{
            "title": "Merge release v${{ github.ref_name }}",
            "body": "Release v${{ github.ref_name }}",
            "head": "merge/v${{ github.ref_name }}",
            "base": "master"
          }'