on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

name: On Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Merge Branch
        run: |
          git checkout release/v${{ github.ref_name }}
          git checkout -b merge/v${{ github.ref_name }}
          git push origin merge/v${{ github.ref_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: merge/v${{ github.ref_name }}
          title: "Merge release v${{ github.ref_name }}"
          body: |
            ## Merge release ${{ github.ref_name }}
            
            This is an automated pull request created for release ${{ github.ref_name }}.
            
            ### Changes
            - Release version: ${{ github.ref_name }}
            - Created from tag: ${{ github.ref }}
            
            Please review and merge this pull request to update the master branch with the release changes.
          commit-message: "Release ${{ github.ref_name }}"
          delete-branch: true