on:
  pull_request:
    paths:
      - rust/**

name: Rust checks

jobs:
#  Embedded:
#    runs-on: ubuntu-latest
#    env:
#      RUSTFLAGS: "-C link-arg=-Tlink.x"
#      CARGO_TARGET_THUMBV7M_NONE_EABI_RUNNER: "qemu-system-arm -cpu cortex-m3 -machine mps2-an385 -nographic -semihosting-config enable=on,target=native -kernel"
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Set up QEMU
#        run: sudo apt update && sudo apt install -y qemu-system-arm gcc-arm-none-eabi
#      - name: Checkout Toolchain
#        uses: dtolnay/rust-toolchain@nightly
#        with:
#          targets: thumbv7m-none-eabi
#      - name: Install src
#        run: rustup component add rust-src
#      - name: Install protobuf compiler
#        run: sudo apt-get install -y protobuf-compiler
#      - name: Run rust/apps/bitcoin
#        run: cd rust/apps/bitcoin/embedded && cargo run --target thumbv7m-none-eabi
#      - name: Run rust/apps/solana
#        run: cd rust/apps/solana/embedded && cargo run --target thumbv7m-none-eabi

  RustfmtCheck:
    name: Fmt Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-26
          override: true
          target: x86_64-apple-darwin
          components: rustfmt

      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Run rust/apps/bitcoin
        run: cd rust/apps/bitcoin && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/apps/ethereum
        run: cd rust/apps/ethereum && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/apps/solana
        run: cd rust/apps/solana && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/apps/cardano
        run: cd rust/apps/cardano && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/apps/tron
        run: cd rust/apps/tron && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/apps/near
        run: cd rust/apps/near && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/apps/xrp
        run: cd rust/apps/xrp && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/apps/cosmos
        run: cd rust/apps/cosmos && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/apps/aptos
        run: cd rust/apps/aptos && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/apps/sui
        run: cd rust/apps/sui && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/apps/utils
        run: cd rust/apps/utils && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/apps/wallets
        run: cd rust/apps/wallets && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/keystore
        run: cd rust/keystore && cargo +nightly-2023-06-26 fmt --check
      - name: Run rust/rust_c
        run: cd rust/rust_c && cargo +nightly-2023-06-26 fmt --check


  UnitTest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-26
          override: true
          components: rustfmt
          target: x86_64-apple-darwin

      - name: Install protobuf compiler
        run: sudo apt-get install -y protobuf-compiler

      - name: Run rust/apps/bitcoin
        run: cd rust/apps/bitcoin && cargo +nightly-2023-06-26 test
      - name: Run rust/apps/ethereum
        run: cd rust/apps/ethereum && cargo +nightly-2023-06-26 test
      - name: Run rust/apps/solana
        run: cd rust/apps/solana && cargo +nightly-2023-06-26 test
      - name: Run rust/apps/cardano
        run: cd rust/apps/cardano && cargo +nightly-2023-06-26 test
      - name: Run rust/apps/tron
        run: cd rust/apps/tron && cargo +nightly-2023-06-26 test
      - name: Run rust/apps/near
        run: cd rust/apps/near && cargo +nightly-2023-06-26 test
      - name: Run rust/apps/xrp
        run: cd rust/apps/xrp && cargo +nightly-2023-06-26 test
      - name: Run rust/apps/cosmos
        run: cd rust/apps/cosmos && cargo +nightly-2023-06-26 test
      - name: Run rust/apps/aptos
        run: cd rust/apps/aptos && cargo +nightly-2023-06-26 test
      - name: Run rust/apps/sui
        run: cd rust/apps/sui && cargo +nightly-2023-06-26 test
      - name: Run rust/apps/utils
        run: cd rust/apps/utils && cargo +nightly-2023-06-26 test
      - name: Run rust/apps/wallets
        run: cd rust/apps/wallets && cargo +nightly-2023-06-26 test
      - name: Run rust/keystore
        run: cd rust/keystore && cargo +nightly-2023-06-26 test
